### ISSUE TITLE
Is there an any dataset?

### ISSUE THREAD

**Issue by ugonfor** [oalieno/asm2vec-pytorch#1]
I wanna test this model.
But, I cannot find any dataset on this repository.

Which binary you use as a dataset? Could you please update it on repository or etc. ?

**Comment by oalieno** [comment]
I currently use the following command to generate the dataset, which extracts the assembly functions from binary under `/bin`. You can try to generate them yourself.

```
python bin2asm.py -i /bin/ -o asm/
```

**Comment by oalieno** [comment]
I am considering adding coreutils as dataset and put it in the release page for download.
The dataset will be generated by compiling with `-O0, -O1, -O2, -O3` different optimization flags.

**Comment by ugonfor** [comment]
Thank you for your kindful answer.
I confirmed that it rightly works. 👍🏻
