### ISSUE TITLE
Missing Functions?

### ISSUE THREAD

**Issue by MGYN** [oalieno/asm2vec-pytorch#9]
I am trying the tool to get all functions embedding in a binary file, and the file has 10 thousand functions, but the tool can only get a few of them and missed about 9000 functions. I found that many functions in the symbol table are missed and many offsets are different from the idea pro, seems the function results in **bin2asm.py** are not a real function.

The difference as follow:

![1616078208(1)](https://user-images.githubusercontent.com/37731495/111645033-57a7e100-883b-11eb-8b36-babaf3086f09.png)
![1616078281(1)](https://user-images.githubusercontent.com/37731495/111645062-5b3b6800-883b-11eb-8ba1-349ece9747e2.png)

The missed functions in the symbol table showed in IDA as follow:

![1616078734(1)](https://user-images.githubusercontent.com/37731495/111645784-077d4e80-883c-11eb-8322-fa42c8ba2a48.png)
![1616078702(1)](https://user-images.githubusercontent.com/37731495/111645803-0b10d580-883c-11eb-858e-c5069877ec97.png)

```
    functions, tokens_new = asm2vec.utils.load_data(data)
    for f in functions:
        print(f.meta)
```

Why does this happen? And Is there a solution?
Besides, my goal is to get all functions embedding in a file and get all the embedding in a tensor or a NumPy with unknown numbers, but maybe I can only get the specific numbers once. I don't know much about the torch, so what can I do?
Such as get the first three but I can't get the 0 to function number.

```
v1 = model.to('cpu').embeddings_f(torch.tensor([0,2,3]))
print(v1)
```

**Comment by MGYN** [comment]
Sorry, I made a mistake with the function miss. But I also wonder to know how can I get all the embedding in a tensor or a NumPy rather than get the specific numbers once.
Thanks!

**Comment by oalieno** [comment]
If you want to get all the embedding you can try this.
```
v1 = model.to('cpu').embeddings_f.weight.clone()
print(v1)
```
